mysite/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('songfy.urls', namespace='songfy')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('api-auth/', include('rest_framework.urls')),
]

songfy/urls.py
from django.urls import path, include
from . import views, viewsets
from rest_framework.routers import DefaultRouter


app_name = 'songfy'

router = DefaultRouter()
router.register('songs', viewsets.SongViewSet)
router.register('artists', viewsets.ArtistViewSet)
router.register('genres', viewsets.GenreViewSet)
router.register('playlists', viewsets.PlaylistViewSet)

urlpatterns = [
    path('', views.home, name='home'),
    path('song/<int:pk>', views.song_detail, name='song_detail'),
    path('artists', views.artist_lst, name='artist_lst'),
    path('genres', views.genre_lst, name='genre_lst'),
    path('playlists', views.playlist_lst, name='playlist_lst'),
    path('artists/<int:pk>', views.artist_song, name='artist_song'),
    path('genres/<int:pk>', views.genre_song, name='genre_song'),
    path('playlists/<int:pk>', views.playlist_song, name='playlist_song'),
    path('song/new', views.add_song, name='add_song'),
    path('song/edit/<int:pk>', views.edit_song, name='edit_song'),
    path('artist/new', views.add_artist, name='add_artist'),
    path('genre/new', views.add_genre, name='add_genre'),
    path('playlist/new', views.add_playlist, name='add_playlist'),
    path('playlist/<int:pk>/edit', views.edit_playlist, name='edit_playlist'),
    path('song/<int:pk>/delete', views.song_delete, name='song_delete'),
    path('artist/<int:pk>/delete', views.artist_delete, name='artist_delete'),
    path('genre/<int:pk>/delete', views.genre_delete, name='genre_delete'),
    path('playlist/<int:pk>/delete', views.playlist_delete, name='playlist_delete'),
    path('signup', views.signup, name='signup'),
    path('api/', include(router.urls)),
    path('api-auth/', include('rest_framework.urls')),
]

songfy/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.


class BaseModel(models.Model):
    created_date = models.DateTimeField(auto_now_add=True, editable=False)
    modified_date = models.DateTimeField(auto_now=True, editable=False)

    class Meta:
        abstract = True


class Genre(BaseModel):
    name = models.CharField(max_length=30)
    user = models.ForeignKey(User, on_delete=models.CASCADE, default=1)

    def __str__(self):
        return self.name


class Artist(BaseModel):
    name = models.CharField(max_length=30)
    user = models.ForeignKey(User, on_delete=models.CASCADE, default=1)

    def __str__(self):
        return self.name


class Song(BaseModel):
    title = models.CharField(max_length=50)
    duration = models.DurationField()
    genre = models.ForeignKey(Genre, on_delete=models.CASCADE, related_name='songs')
    artist = models.ForeignKey(Artist, on_delete=models.CASCADE, related_name='songs')
    user = models.ForeignKey(User, on_delete=models.CASCADE, default=1)

    def __str__(self):
        return self.title


class Playlist(BaseModel):
    name = models.CharField(max_length=30)
    song = models.ManyToManyField(Song)
    user = models.ForeignKey(User, on_delete=models.CASCADE, default=1)

    def __str__(self):
        return self.name

songfy/forms.py
from django import forms
from .models import Song, Artist, Genre, Playlist


class SongForm(forms.ModelForm):

    class Meta:
        model = Song
        fields = ('title', 'duration', 'genre', 'artist')

    def __init__(self, user, *args, **kwargs):
        super(SongForm, self).__init__(*args, **kwargs)
        self.fields['genre'].queryset = Genre.objects.filter(user=user)
        self.fields['artist'].queryset = Artist.objects.filter(user=user)


class ArtistForm(forms.ModelForm):

    class Meta:
        model = Artist
        fields = ('name', )


class GenreForm(forms.ModelForm):

    class Meta:
        model = Genre
        fields = ('name', )


class PlaylistForm(forms.ModelForm):

    class Meta:
        model = Playlist
        fields = ('name', 'song')
        widgets = {'song': forms.CheckboxSelectMultiple}

songfy/views.py
from django.shortcuts import render, get_object_or_404, redirect
from .models import Song, Artist, Genre, Playlist
from .forms import SongForm, ArtistForm, GenreForm, PlaylistForm
from django.contrib.auth.decorators import login_required
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth import login, authenticate


@login_required
def home(request):
    if request.user.is_authenticated:
        songs = Song.objects.all().filter(user=request.user).order_by('title')
        return render(request, 'songfy/home.html', {'songs': songs})


def song_detail(request, pk):
    song = get_object_or_404(Song, pk=pk)
    return render(request, 'songfy/song_detail.html', {'song': song})


@login_required
def artist_lst(request):
    if request.user.is_authenticated:
        artists = Artist.objects.all().filter(user=request.user).order_by('name')
        return render(request, 'songfy/artist.html', {'artists': artists})


@login_required
def genre_lst(request):
    if request.user.is_authenticated:
        genres = Genre.objects.all().filter(user=request.user).order_by('name')
        return render(request, 'songfy/genre.html', {'genres': genres})


@login_required
def playlist_lst(request):
    if request.user.is_authenticated:
        playlists = Playlist.objects.all().filter(user=request.user).order_by('name')
        return render(request, 'songfy/playlist.html', {'playlists': playlists})


def artist_song(request, pk):
    if request.user.is_authenticated:
        artist_obj = get_object_or_404(Artist, pk=pk)
        artists = Artist.objects.all().filter(user=request.user).order_by('name')
        return render(request, 'songfy/artist_song.html', {'artist_obj': artist_obj, 'artists': artists})


def genre_song(request, pk):
    if request.user.is_authenticated:
        genre_obj = get_object_or_404(Genre, pk=pk)
        genres = Genre.objects.all().filter(user=request.user).order_by('name')
        return render(request, 'songfy/genre_song.html', {'genre_obj': genre_obj, 'genres': genres})


def playlist_song(request, pk):
    if request.user.is_authenticated:
        playlist_obj = get_object_or_404(Playlist, pk=pk)
        playlists = Playlist.objects.all().filter(user=request.user).order_by('name')
        return render(request, 'songfy/playlist_song.html', {'playlist_obj': playlist_obj, 'playlists': playlists})


@login_required
def add_song(request):
    if request.method == 'POST':
        form = SongForm(request.user, request.POST)
        if form.is_valid():
            song = form.save(commit=False)
            song.user = request.user
            song.save()
            return redirect('/')

    else:
        form = SongForm(request.user)
    return render(request, 'songfy/add_edit_song.html', {'form': form})


@login_required
def edit_song(request, pk):
    song = get_object_or_404(Song, pk=pk)
    if request.method == 'POST':
        form = SongForm(request.POST, instance=song)
        if form.is_valid():
            form.save()
            return redirect('songfy:song_detail', pk=song.id)
    else:
        form = SongForm(instance=song)
    return render(request, 'songfy/add_edit_song.html', {'form': form})


@login_required
def add_artist(request):
    if request.method == "POST":
        form = ArtistForm(request.POST)
        if form.is_valid():
            artist = form.save(commit=False)
            artist.user = request.user
            artist.save()
            return redirect('/artists')
    else:
        form = ArtistForm()
    return render(request, 'songfy/add_artist.html', {'form': form})


@login_required
def add_genre(request):
    if request.method == "POST":
        form = GenreForm(request.POST)
        if form.is_valid():
            genre = form.save(commit=False)
            genre.user = request.user
            genre.save()
            return redirect('/genres')
    else:
        form = GenreForm()
    return render(request, 'songfy/add_genre.html', {'form': form})


@login_required
def add_playlist(request):
    if request.method == "POST":
        form = PlaylistForm(request.POST)
        if form.is_valid():
            playlist = form.save(commit=False)
            playlist.user = request.user
            playlist.save()
            return redirect('/playlists')
    else:
        form = PlaylistForm()
    return render(request, 'songfy/add_playlist.html', {'form': form})


@login_required
def edit_playlist(request, pk):
    playlist = get_object_or_404(Playlist, pk=pk)
    if request.method == "POST":
        form = PlaylistForm(request.POST, instance=playlist)
        if form.is_valid():
            form.save()
            return redirect('songfy:playlist_song', pk=playlist.id)
    else:
        form = PlaylistForm(instance=playlist)
    return render(request, 'songfy/add_playlist.html', {'form': form})


@login_required
def song_delete(request, pk):
    song = get_object_or_404(Song, pk=pk)
    song.delete()
    return redirect('/')


@login_required
def artist_delete(request, pk):
    artist = get_object_or_404(Artist, pk=pk)
    artist.delete()
    return redirect('/artists')


@login_required
def genre_delete(request, pk):
    genre = get_object_or_404(Genre, pk=pk)
    genre.delete()
    return redirect('/genres')


@login_required
def playlist_delete(request, pk):
    playlist = get_object_or_404(Playlist, pk=pk)
    playlist.delete()
    return redirect('/playlists')


def signup(request):
    if request.method == 'POST':
        form = UserCreationForm(request.POST)
        if form.is_valid():
            form.save()
            username = form.cleaned_data.get('username')
            raw_password = form.cleaned_data.get('password1')
            user = authenticate(username=username, password=raw_password)
            login(request, user)
            return redirect('/')
    else:
        form = UserCreationForm()
    return render(request, 'songfy/signup.html', {'form': form})

songfy/templates/songfy/add_edit_song.html
{% extends 'songfy/base.html' %}
{% block content %}
<div class="container">
	<form method="post">
		{% csrf_token %}
		{% include 'songfy/bs4_form.html' with form=form %}
  		<button type="submit" class="btn bg-warning btn-primary">Submit</button>
	</form>
</div>
{% endblock %}

songfy/templates/songfy/add_genre.html
{% extends 'songfy/base.html' %}
{% block content %}
<form method="post">
	{% csrf_token %}
	{% include 'songfy/bs4_form.html' with form=form %}
  <button type="submit" class="btn bg-warning btn-primary">Submit</button>
</form>
{% endblock %}

songfy/templates/songfy/add_playlist.html
{% extends 'songfy/base.html' %}
{% block content %}
<form method="post" novalidate>
  {% csrf_token %}
  {% include 'songfy/bs4_form.html' with form=form %}
  <button type="submit" class="btn bg-warning btn-primary">Submit</button>
</form>
{% endblock %}

songfy/templates/songfy/artist.html
{% extends 'songfy/base.html' %}
{% block content %}
<div class="container">
		<div class="artist container">
			<table class="table">
				{% for artist in artists %}
					<tr>
						<td>
							<a href="{% url 'songfy:artist_song' artist.id %}">{{ artist.name }}</a>
						</td>
						<td class="delete" align="right">
							<a href="{% url 'songfy:artist_delete' artist.id %}">Delete</a>
						</td>
					</tr>
				{% endfor %}	
			</table>				
			<a href="{% url 'songfy:add_artist' %}">
				<button type="button" class="bg-warning btn btn-primary">Add New</button>
			</a>
		</div>
</div>
{% endblock %}

songfy/templates/songfy/artist_song.html
{% extends 'songfy/base.html' %}
{% block content %}
<br/>
<div class="container">
	<div class="row">
	  <div class="col-3">
	  	<h2>Artists</h2>
	    <div class="nav flex-column nav-pills" id="v-pills-tab" role="tablist" aria-orientation="vertical">
	    	{% for artist in artists %}
	    		<a class="nav-link {% if artist.id == artist_obj.id %}active bg-warning{% endif %}" id="v-pills-home-tab" data-toggle="pill" href="{% url 'songfy:artist_song' artist.id %}" role="tab" aria-controls="v-pills-home" aria-selected="true">{{ artist.name }}</a>
	    	{% endfor %}
	    </div>
	  </div>
	  <div class="col-9">
	    <div class="tab-content" id="v-pills-tabContent">
	      <div class="tab-pane fade show active" id="v-pills-home" role="tabpanel" aria-labelledby="v-pills-home-tab">
	      	<table class="table">
	      		<thead>
		      		<tr>
		      			<th scope="col">Songs</th>
		      		</tr>
	      		</thead>
	      		<tbody>
	      		{% for song in artist_obj.songs.all %}
	      			<tr>
	      				<td><a href="{% url 'songfy:song_detail' song.id %}">{{ song }}</a></td>
	      			</tr>
	      		{% endfor %}
	      		</tbody>
	      	</table>
	      </div>
	    </div>
	  </div>
	</div>
</div>
{% endblock %}

songfy/templates/songfy/base.html
{% load staticfiles %}
{% load widget_tweaks %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>Songfy</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.2/css/bootstrap.min.css" integrity="sha384-Smlep5jCw/wG7hdkwQ/Z5nLIefveQRIY9nfy6xoR1uRYBtpZgI6339F5dgvm/e9B" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'css/songfy.css' %}">
</head>
<body>
        <nav class="navbar navbar-expand-lg navbar-light bg-light">
            <a class="navbar-brand" href="{% url 'songfy:home' %}">Songfy</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
            </button>

            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav mr-auto">
                    <li class="nav-item active">
                        <a class="nav-link" href="{% url 'songfy:home' %}">Home <span class="sr-only">(current)</span></a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'songfy:artist_lst' %}">Artists</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'songfy:genre_lst' %}">Genres</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link disabled" href="{% url 'songfy:playlist_lst' %}">Playlists</a>
                    </li>
                </ul>
                <div class="loginout">
                {% if user.is_authenticated %}
                    <span>
                        <p>Hello {{ user.username }}!<small><a href="{% url 'logout' %}">Logout</a></small></p>
                    </span>
                {% else %}
                    <span>
                        <small>
                            <p>
                            <a href="{% url 'login' %}">Login</a>/<a href="{% url 'songfy:signup' %}">Signup</a>
                            </p>
                        </small>
                    </span>

                {% endif %}
                <span class="navbar-text">
                    Organise Your Song Collection
                </span>
                </div>
            </div>
        </nav>
        <div class="full-page-wrapper">
            {% block content %}
            {% endblock %}
        </div>
    <footer>
        <nav class="navbar navbar-expand-lg navbar-light bg-light">
            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav mr-auto">
                    <li class="nav-item active">
                        <a class="nav-link" href="{% url 'songfy:home' %}">Home <span class="sr-only">(current)</span></a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'songfy:artist_lst' %}">Artists</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'songfy:genre_lst' %}">Genres</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link disabled" href="{% url 'songfy:playlist_lst' %}">Playlists</a>
                    </li>
                </ul>
                <span class="navbar-text">
                    <small>&copy; Songfy</small>
                </span>
            </div>
        </nav>
    </footer>
</body>
</html>

songfy/templates/songfy/bs4_form.html
{% load widget_tweaks %}

{% for hidden_field in form.hidden_fields %}
  {{ hidden_field }}
{% endfor %}

{% if form.non_field_errors %}
  <div class="alert alert-danger" role="alert">
    {% for error in form.non_field_errors %}
      {{ error }}
    {% endfor %}
  </div>
{% endif %}

{% for field in form.visible_fields %}
  <div class="form-group">
    {{ field.label_tag }}

    {% if form.is_bound %}
      {% if field.errors %}
        {% render_field field class="form-control is-invalid" %}
        {% for error in field.errors %}
          <div class="invalid-feedback">
            {{ error }}
          </div>
        {% endfor %}
      {% else %}
        {% render_field field class="form-control is-valid" %}
      {% endif %}
    {% else %}
      {% render_field field class="form-control" %}
    {% endif %}

    {% if field.help_text %}
      <small class="form-text text-muted">{{ field.help_text }}</small>
    {% endif %}
  </div>
{% endfor %}

songfy/templates/songfy/genre.html
{% extends 'songfy/base.html' %}
{% block content %}
<div class="container">
	<table class="table">
		{% for genre in genres %}
			<tr>
				<td>
					<a href="{% url 'songfy:genre_song' genre.id %}">{{ genre.name }}</a>
				</td>
				<td class="delete" align="right">
					<a href="{% url 'songfy:genre_delete' genre.id %}">Delete</a>			
				</td>
			</tr>
		{% endfor %}
	</table>
		<a href="{% url 'songfy:add_genre' %}">
			<button type="button" class="btn btn-primary bg-warning">Add New</button>
		</a>
</div>
{% endblock %}

songfy/templates/songfy/genre_song.html
{% extends 'songfy/base.html' %}
{% block content %}
<br/>
<div class="container">
	<div class="row">
	  <div class="col-3">
	  	<h2>Artists</h2>
	    <div class="nav flex-column nav-pills" id="v-pills-tab" role="tablist" aria-orientation="vertical">
	    	{% for genre in genres %}
	    		<a class="nav-link {% if genre.id == genre_obj.id %}active bg-warning{% endif %}" id="v-pills-home-tab" data-toggle="pill" href="{% url 'songfy:genre_song' genre.id %}" role="tab" aria-controls="v-pills-home" aria-selected="true">{{ genre.name }}</a>
	    	{% endfor %}
	    </div>
	  </div>
	  <div class="col-9">
	    <div class="tab-content" id="v-pills-tabContent">
	      <div class="tab-pane fade show active" id="v-pills-home" role="tabpanel" aria-labelledby="v-pills-home-tab">
	      	<table class="table">
	      		<thead>
		      		<tr>
		      			<th scope="col">Songs</th>
		      		</tr>
	      		</thead>
	      		<tbody>
	      		{% for song in genre_obj.songs.all %}
	      			<tr>
	      				<td><a href="{% url 'songfy:song_detail' song.id %}">{{ song }}</a></td>
	      			</tr>
	      		{% endfor %}
	      		</tbody>
	      	</table>
	      </div>
	    </div>
	  </div>
	</div>
</div>
{% endblock %}

songfy/templates/songfy/home.html
{% extends 'songfy/base.html' %}
{% block content %}
    <section class="container">
        <table class="table">
            <th scope="col">Song</th>
            <th scope="col">Genre</th>
            <th scope="col">Artist</th>
            <th scope="col">Duration</th>
            {% for song in songs %}
             <tr>
                <td><a href="{% url 'songfy:song_detail' song.id %}">{{ song.title }}</a></td>
                <td><a href="{% url 'songfy:genre_song' song.genre.id %}">{{ song.genre }}</a></td>
                <td><a href="{% url 'songfy:artist_song' song.artist.id %}">{{ song.artist }}</a></td>
                <td>{{ song.duration}}</td>
             </tr>
             {% endfor %}
        </table>
        <a href="{% url 'songfy:add_song' %}">
            <button type="button" class="btn  bg-warning btn-primary">Add New</button>
        </a>
    </section>
{% endblock %}

songfy/templates/songfy/playlist.html
{% extends 'songfy/base.html' %}
{% block content %}
<div class="container">
		<table class="table">
			{% for playlist in playlists %}
				<tr>
					<td>
						<a href="{% url 'songfy:playlist_song' playlist.id %}">{{ playlist.name }}</a>
					</td>
					<td  class="delete" align="right">
						<a href="{% url 'songfy:playlist_delete' playlist.id %}">Delete</a>
					</td>
				</tr>
			{% endfor %}
		</table>
			<a href="{% url 'songfy:add_playlist' %}">
				<button type="button" class="btn bg-warning btn-primary">Make New</button>
			</a>
</div>
{% endblock %}

songfy/templates/songfy/playlist_song.html
{% extends 'songfy/base.html' %}
{% block content %}
<br/>
<div class="container">
	<div class="row">
	  <div class="col-3">
	  	<h2>playlists</h2>
	    <div class="nav flex-column nav-pills" id="v-pills-tab" role="tablist" aria-orientation="vertical">
	    	{% for playlist in playlists %}
	    		<a class="nav-link {% if playlist.id == playlist_obj.id %}active bg-warning{% endif %}" id="v-pills-home-tab" data-toggle="pill" href="{% url 'songfy:playlist_song' playlist.id %}" role="tab" aria-controls="v-pills-home" aria-selected="true">{{ playlist.name }}</a>
	    	{% endfor %}
	    </div>
	  </div>
	  <div class="col-9">
	    <div class="tab-content" id="v-pills-tabContent">
	      <div class="tab-pane fade show active" id="v-pills-home" role="tabpanel" aria-labelledby="v-pills-home-tab">
	      	<table class="table">
	      		<thead>
		      		<tr>
		      			<th scope="col">Songs</th>
		      		</tr>
	      		</thead>
	      		<tbody>
	      		{% for song in playlist_obj.song.all %}
	      			<tr>
	      				<td><a href="{% url 'songfy:song_detail' song.id %}">{{ song }}</a></td>
	      			</tr>
	      		{% endfor %}
	      		</tbody>
	      	</table>
	      </div>
	      <button type="button" class="btn  bg-warning btn-primary">
	      	<a href="{% url 'songfy:edit_playlist' playlist_obj.id %}">Add Song</a>
	      </button>
	    </div>
	  </div>
	</div>
</div>
{% endblock %}

songfy/templates/songfy/signup.html
{% extends 'songfy/base.html' %}

{% block content %}
  <h2>Sign up</h2>
  <form method="post">
		{% csrf_token %}
		{% include 'songfy/bs4_form.html' with form=form %}
  		<button type="submit" class="btn bg-warning btn-primary">Submit</button>
	</form>
{% endblock %}

songfy/templates/songfy/song_detail.html
{% extends 'songfy/base.html' %}
{% block content %}
<div class='container'>
	<div class="row">
		<div class="col-6">
			<h5>Title {{ song.title }}</h5>
			<p>Artist {{ song.artist }}</p>
			<p>Genre {{ song.genre }}</p>
			<p>Duration {{ song.duration }}</p>
			<a href="{% url 'songfy:edit_song' song.id %}">Edit</a>
			<a href="{% url 'songfy:song_delete' song.id %}">Delete</a>
		</div>
		
	</div>
</div>

{% endblock %}